import unittest
from unittest import mock

from retrieve_repo import get_commits, get_repo, get_api, get_output


class MockedRes:
    def __init__(self, res):
        self.res = res

    def json(self):
        return self.res


class TestRetrieve_Repo(unittest.TestCase):

    @mock.patch('retrieve_repo.requests.get')
    def test_get_api(self, mocked_req):
        response = [{'id': 241715376, 'node_id': 'MDEwOlJlcG9zaXRvcnkyNDE3MTUzNzY=', 'name': 'GitHubApi567',
                     'full_name': 'cdp2323/GitHubApi567', 'private': False,
                     'owner': {'login': 'cdp2323', 'id': 57602737, 'node_id': 'MDQ6VXNlcjU3NjAyNzM3',
                               'avatar_url': 'https://avatars1.githubusercontent.com/u/57602737?v=4', 'gravatar_id': '',
                               'url': 'https://api.github.com/users/cdp2323', 'html_url': 'https://github.com/cdp2323',
                               'followers_url': 'https://api.github.com/users/cdp2323/followers',
                               'following_url': 'https://api.github.com/users/cdp2323/following{/other_user}',
                               'gists_url': 'https://api.github.com/users/cdp2323/gists{/gist_id}',
                               'starred_url': 'https://api.github.com/users/cdp2323/starred{/owner}{/repo}',
                               'subscriptions_url': 'https://api.github.com/users/cdp2323/subscriptions',
                               'organizations_url': 'https://api.github.com/users/cdp2323/orgs',
                               'repos_url': 'https://api.github.com/users/cdp2323/repos',
                               'events_url': 'https://api.github.com/users/cdp2323/events{/privacy}',
                               'received_events_url': 'https://api.github.com/users/cdp2323/received_events',
                               'type': 'User', 'site_admin': False},
                     'html_url': 'https://github.com/cdp2323/GitHubApi567', 'description': None, 'fork': False,
                     'url': 'https://api.github.com/repos/cdp2323/GitHubApi567',
                     'forks_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/forks',
                     'keys_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/keys{/key_id}',
                     'collaborators_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/collaborators{/collaborator}',
                     'teams_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/teams',
                     'hooks_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/hooks',
                     'issue_events_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/issues/events{/number}',
                     'events_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/events',
                     'assignees_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/assignees{/user}',
                     'branches_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/branches{/branch}',
                     'tags_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/tags',
                     'blobs_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/git/blobs{/sha}',
                     'git_tags_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/git/tags{/sha}',
                     'git_refs_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/git/refs{/sha}',
                     'trees_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/git/trees{/sha}',
                     'statuses_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/statuses/{sha}',
                     'languages_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/languages',
                     'stargazers_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/stargazers',
                     'contributors_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/contributors',
                     'subscribers_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/subscribers',
                     'subscription_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/subscription',
                     'commits_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/commits{/sha}',
                     'git_commits_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/git/commits{/sha}',
                     'comments_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/comments{/number}',
                     'issue_comment_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/issues/comments{/number}',
                     'contents_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/contents/{+path}',
                     'compare_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/compare/{base}...{head}',
                     'merges_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/merges',
                     'archive_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/{archive_format}{/ref}',
                     'downloads_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/downloads',
                     'issues_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/issues{/number}',
                     'pulls_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/pulls{/number}',
                     'milestones_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/milestones{/number}',
                     'notifications_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/notifications{?since,all,participating}',
                     'labels_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/labels{/name}',
                     'releases_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/releases{/id}',
                     'deployments_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/deployments',
                     'created_at': '2020-02-19T20:11:27Z', 'updated_at': '2020-02-20T00:05:44Z',
                     'pushed_at': '2020-02-26T21:07:29Z', 'git_url': 'git://github.com/cdp2323/GitHubApi567.git',
                     'ssh_url': 'git@github.com:cdp2323/GitHubApi567.git',
                     'clone_url': 'https://github.com/cdp2323/GitHubApi567.git',
                     'svn_url': 'https://github.com/cdp2323/GitHubApi567', 'homepage': None, 'size': 30,
                     'stargazers_count': 0, 'watchers_count': 0, 'language': 'Python', 'has_issues': True,
                     'has_projects': True, 'has_downloads': True, 'has_wiki': True, 'has_pages': False,
                     'forks_count': 0, 'mirror_url': None, 'archived': False, 'disabled': False, 'open_issues_count': 0,
                     'license': None, 'forks': 0, 'open_issues': 0, 'watchers': 0, 'default_branch': 'master'},
                    {'id': 236403982, 'node_id': 'MDEwOlJlcG9zaXRvcnkyMzY0MDM5ODI=', 'name': 'hw567',
                     'full_name': 'cdp2323/hw567', 'private': False,
                     'owner': {'login': 'cdp2323', 'id': 57602737, 'node_id': 'MDQ6VXNlcjU3NjAyNzM3',
                               'avatar_url': 'https://avatars1.githubusercontent.com/u/57602737?v=4', 'gravatar_id': '',
                               'url': 'https://api.github.com/users/cdp2323', 'html_url': 'https://github.com/cdp2323',
                               'followers_url': 'https://api.github.com/users/cdp2323/followers',
                               'following_url': 'https://api.github.com/users/cdp2323/following{/other_user}',
                               'gists_url': 'https://api.github.com/users/cdp2323/gists{/gist_id}',
                               'starred_url': 'https://api.github.com/users/cdp2323/starred{/owner}{/repo}',
                               'subscriptions_url': 'https://api.github.com/users/cdp2323/subscriptions',
                               'organizations_url': 'https://api.github.com/users/cdp2323/orgs',
                               'repos_url': 'https://api.github.com/users/cdp2323/repos',
                               'events_url': 'https://api.github.com/users/cdp2323/events{/privacy}',
                               'received_events_url': 'https://api.github.com/users/cdp2323/received_events',
                               'type': 'User', 'site_admin': False}, 'html_url': 'https://github.com/cdp2323/hw567',
                     'description': None, 'fork': False, 'url': 'https://api.github.com/repos/cdp2323/hw567',
                     'forks_url': 'https://api.github.com/repos/cdp2323/hw567/forks',
                     'keys_url': 'https://api.github.com/repos/cdp2323/hw567/keys{/key_id}',
                     'collaborators_url': 'https://api.github.com/repos/cdp2323/hw567/collaborators{/collaborator}',
                     'teams_url': 'https://api.github.com/repos/cdp2323/hw567/teams',
                     'hooks_url': 'https://api.github.com/repos/cdp2323/hw567/hooks',
                     'issue_events_url': 'https://api.github.com/repos/cdp2323/hw567/issues/events{/number}',
                     'events_url': 'https://api.github.com/repos/cdp2323/hw567/events',
                     'assignees_url': 'https://api.github.com/repos/cdp2323/hw567/assignees{/user}',
                     'branches_url': 'https://api.github.com/repos/cdp2323/hw567/branches{/branch}',
                     'tags_url': 'https://api.github.com/repos/cdp2323/hw567/tags',
                     'blobs_url': 'https://api.github.com/repos/cdp2323/hw567/git/blobs{/sha}',
                     'git_tags_url': 'https://api.github.com/repos/cdp2323/hw567/git/tags{/sha}',
                     'git_refs_url': 'https://api.github.com/repos/cdp2323/hw567/git/refs{/sha}',
                     'trees_url': 'https://api.github.com/repos/cdp2323/hw567/git/trees{/sha}',
                     'statuses_url': 'https://api.github.com/repos/cdp2323/hw567/statuses/{sha}',
                     'languages_url': 'https://api.github.com/repos/cdp2323/hw567/languages',
                     'stargazers_url': 'https://api.github.com/repos/cdp2323/hw567/stargazers',
                     'contributors_url': 'https://api.github.com/repos/cdp2323/hw567/contributors',
                     'subscribers_url': 'https://api.github.com/repos/cdp2323/hw567/subscribers',
                     'subscription_url': 'https://api.github.com/repos/cdp2323/hw567/subscription',
                     'commits_url': 'https://api.github.com/repos/cdp2323/hw567/commits{/sha}',
                     'git_commits_url': 'https://api.github.com/repos/cdp2323/hw567/git/commits{/sha}',
                     'comments_url': 'https://api.github.com/repos/cdp2323/hw567/comments{/number}',
                     'issue_comment_url': 'https://api.github.com/repos/cdp2323/hw567/issues/comments{/number}',
                     'contents_url': 'https://api.github.com/repos/cdp2323/hw567/contents/{+path}',
                     'compare_url': 'https://api.github.com/repos/cdp2323/hw567/compare/{base}...{head}',
                     'merges_url': 'https://api.github.com/repos/cdp2323/hw567/merges',
                     'archive_url': 'https://api.github.com/repos/cdp2323/hw567/{archive_format}{/ref}',
                     'downloads_url': 'https://api.github.com/repos/cdp2323/hw567/downloads',
                     'issues_url': 'https://api.github.com/repos/cdp2323/hw567/issues{/number}',
                     'pulls_url': 'https://api.github.com/repos/cdp2323/hw567/pulls{/number}',
                     'milestones_url': 'https://api.github.com/repos/cdp2323/hw567/milestones{/number}',
                     'notifications_url': 'https://api.github.com/repos/cdp2323/hw567/notifications{?since,all,participating}',
                     'labels_url': 'https://api.github.com/repos/cdp2323/hw567/labels{/name}',
                     'releases_url': 'https://api.github.com/repos/cdp2323/hw567/releases{/id}',
                     'deployments_url': 'https://api.github.com/repos/cdp2323/hw567/deployments',
                     'created_at': '2020-01-27T01:52:58Z', 'updated_at': '2020-01-30T02:28:22Z',
                     'pushed_at': '2020-01-27T01:53:02Z', 'git_url': 'git://github.com/cdp2323/hw567.git',
                     'ssh_url': 'git@github.com:cdp2323/hw567.git', 'clone_url': 'https://github.com/cdp2323/hw567.git',
                     'svn_url': 'https://github.com/cdp2323/hw567', 'homepage': None, 'size': 0, 'stargazers_count': 0,
                     'watchers_count': 0, 'language': 'Python', 'has_issues': True, 'has_projects': True,
                     'has_downloads': True, 'has_wiki': True, 'has_pages': False, 'forks_count': 0, 'mirror_url': None,
                     'archived': False, 'disabled': False, 'open_issues_count': 0, 'license': None, 'forks': 0,
                     'open_issues': 0, 'watchers': 0, 'default_branch': 'master'},
                    {'id': 220853365, 'node_id': 'MDEwOlJlcG9zaXRvcnkyMjA4NTMzNjU=', 'name': 'hw810',
                     'full_name': 'cdp2323/hw810', 'private': False,
                     'owner': {'login': 'cdp2323', 'id': 57602737, 'node_id': 'MDQ6VXNlcjU3NjAyNzM3',
                               'avatar_url': 'https://avatars1.githubusercontent.com/u/57602737?v=4', 'gravatar_id': '',
                               'url': 'https://api.github.com/users/cdp2323', 'html_url': 'https://github.com/cdp2323',
                               'followers_url': 'https://api.github.com/users/cdp2323/followers',
                               'following_url': 'https://api.github.com/users/cdp2323/following{/other_user}',
                               'gists_url': 'https://api.github.com/users/cdp2323/gists{/gist_id}',
                               'starred_url': 'https://api.github.com/users/cdp2323/starred{/owner}{/repo}',
                               'subscriptions_url': 'https://api.github.com/users/cdp2323/subscriptions',
                               'organizations_url': 'https://api.github.com/users/cdp2323/orgs',
                               'repos_url': 'https://api.github.com/users/cdp2323/repos',
                               'events_url': 'https://api.github.com/users/cdp2323/events{/privacy}',
                               'received_events_url': 'https://api.github.com/users/cdp2323/received_events',
                               'type': 'User', 'site_admin': False}, 'html_url': 'https://github.com/cdp2323/hw810',
                     'description': None, 'fork': False, 'url': 'https://api.github.com/repos/cdp2323/hw810',
                     'forks_url': 'https://api.github.com/repos/cdp2323/hw810/forks',
                     'keys_url': 'https://api.github.com/repos/cdp2323/hw810/keys{/key_id}',
                     'collaborators_url': 'https://api.github.com/repos/cdp2323/hw810/collaborators{/collaborator}',
                     'teams_url': 'https://api.github.com/repos/cdp2323/hw810/teams',
                     'hooks_url': 'https://api.github.com/repos/cdp2323/hw810/hooks',
                     'issue_events_url': 'https://api.github.com/repos/cdp2323/hw810/issues/events{/number}',
                     'events_url': 'https://api.github.com/repos/cdp2323/hw810/events',
                     'assignees_url': 'https://api.github.com/repos/cdp2323/hw810/assignees{/user}',
                     'branches_url': 'https://api.github.com/repos/cdp2323/hw810/branches{/branch}',
                     'tags_url': 'https://api.github.com/repos/cdp2323/hw810/tags',
                     'blobs_url': 'https://api.github.com/repos/cdp2323/hw810/git/blobs{/sha}',
                     'git_tags_url': 'https://api.github.com/repos/cdp2323/hw810/git/tags{/sha}',
                     'git_refs_url': 'https://api.github.com/repos/cdp2323/hw810/git/refs{/sha}',
                     'trees_url': 'https://api.github.com/repos/cdp2323/hw810/git/trees{/sha}',
                     'statuses_url': 'https://api.github.com/repos/cdp2323/hw810/statuses/{sha}',
                     'languages_url': 'https://api.github.com/repos/cdp2323/hw810/languages',
                     'stargazers_url': 'https://api.github.com/repos/cdp2323/hw810/stargazers',
                     'contributors_url': 'https://api.github.com/repos/cdp2323/hw810/contributors',
                     'subscribers_url': 'https://api.github.com/repos/cdp2323/hw810/subscribers',
                     'subscription_url': 'https://api.github.com/repos/cdp2323/hw810/subscription',
                     'commits_url': 'https://api.github.com/repos/cdp2323/hw810/commits{/sha}',
                     'git_commits_url': 'https://api.github.com/repos/cdp2323/hw810/git/commits{/sha}',
                     'comments_url': 'https://api.github.com/repos/cdp2323/hw810/comments{/number}',
                     'issue_comment_url': 'https://api.github.com/repos/cdp2323/hw810/issues/comments{/number}',
                     'contents_url': 'https://api.github.com/repos/cdp2323/hw810/contents/{+path}',
                     'compare_url': 'https://api.github.com/repos/cdp2323/hw810/compare/{base}...{head}',
                     'merges_url': 'https://api.github.com/repos/cdp2323/hw810/merges',
                     'archive_url': 'https://api.github.com/repos/cdp2323/hw810/{archive_format}{/ref}',
                     'downloads_url': 'https://api.github.com/repos/cdp2323/hw810/downloads',
                     'issues_url': 'https://api.github.com/repos/cdp2323/hw810/issues{/number}',
                     'pulls_url': 'https://api.github.com/repos/cdp2323/hw810/pulls{/number}',
                     'milestones_url': 'https://api.github.com/repos/cdp2323/hw810/milestones{/number}',
                     'notifications_url': 'https://api.github.com/repos/cdp2323/hw810/notifications{?since,all,participating}',
                     'labels_url': 'https://api.github.com/repos/cdp2323/hw810/labels{/name}',
                     'releases_url': 'https://api.github.com/repos/cdp2323/hw810/releases{/id}',
                     'deployments_url': 'https://api.github.com/repos/cdp2323/hw810/deployments',
                     'created_at': '2019-11-10T21:24:54Z', 'updated_at': '2019-11-10T23:26:00Z',
                     'pushed_at': '2019-11-16T23:16:47Z', 'git_url': 'git://github.com/cdp2323/hw810.git',
                     'ssh_url': 'git@github.com:cdp2323/hw810.git', 'clone_url': 'https://github.com/cdp2323/hw810.git',
                     'svn_url': 'https://github.com/cdp2323/hw810', 'homepage': None, 'size': 1190,
                     'stargazers_count': 0, 'watchers_count': 0, 'language': 'Python', 'has_issues': True,
                     'has_projects': True, 'has_downloads': True, 'has_wiki': True, 'has_pages': False,
                     'forks_count': 0, 'mirror_url': None, 'archived': False, 'disabled': False, 'open_issues_count': 0,
                     'license': None, 'forks': 0, 'open_issues': 0, 'watchers': 0, 'default_branch': 'master'},
                    {'id': 239021902, 'node_id': 'MDEwOlJlcG9zaXRvcnkyMzkwMjE5MDI=', 'name': 'SSW555DSYZ',
                     'full_name': 'cdp2323/SSW555DSYZ', 'private': False,
                     'owner': {'login': 'cdp2323', 'id': 57602737, 'node_id': 'MDQ6VXNlcjU3NjAyNzM3',
                               'avatar_url': 'https://avatars1.githubusercontent.com/u/57602737?v=4', 'gravatar_id': '',
                               'url': 'https://api.github.com/users/cdp2323', 'html_url': 'https://github.com/cdp2323',
                               'followers_url': 'https://api.github.com/users/cdp2323/followers',
                               'following_url': 'https://api.github.com/users/cdp2323/following{/other_user}',
                               'gists_url': 'https://api.github.com/users/cdp2323/gists{/gist_id}',
                               'starred_url': 'https://api.github.com/users/cdp2323/starred{/owner}{/repo}',
                               'subscriptions_url': 'https://api.github.com/users/cdp2323/subscriptions',
                               'organizations_url': 'https://api.github.com/users/cdp2323/orgs',
                               'repos_url': 'https://api.github.com/users/cdp2323/repos',
                               'events_url': 'https://api.github.com/users/cdp2323/events{/privacy}',
                               'received_events_url': 'https://api.github.com/users/cdp2323/received_events',
                               'type': 'User', 'site_admin': False},
                     'html_url': 'https://github.com/cdp2323/SSW555DSYZ', 'description': 'SSW555 Group Project',
                     'fork': True, 'url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ',
                     'forks_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/forks',
                     'keys_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/keys{/key_id}',
                     'collaborators_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/collaborators{/collaborator}',
                     'teams_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/teams',
                     'hooks_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/hooks',
                     'issue_events_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/issues/events{/number}',
                     'events_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/events',
                     'assignees_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/assignees{/user}',
                     'branches_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/branches{/branch}',
                     'tags_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/tags',
                     'blobs_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/git/blobs{/sha}',
                     'git_tags_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/git/tags{/sha}',
                     'git_refs_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/git/refs{/sha}',
                     'trees_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/git/trees{/sha}',
                     'statuses_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/statuses/{sha}',
                     'languages_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/languages',
                     'stargazers_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/stargazers',
                     'contributors_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/contributors',
                     'subscribers_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/subscribers',
                     'subscription_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/subscription',
                     'commits_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/commits{/sha}',
                     'git_commits_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/git/commits{/sha}',
                     'comments_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/comments{/number}',
                     'issue_comment_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/issues/comments{/number}',
                     'contents_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/contents/{+path}',
                     'compare_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/compare/{base}...{head}',
                     'merges_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/merges',
                     'archive_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/{archive_format}{/ref}',
                     'downloads_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/downloads',
                     'issues_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/issues{/number}',
                     'pulls_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/pulls{/number}',
                     'milestones_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/milestones{/number}',
                     'notifications_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/notifications{?since,all,participating}',
                     'labels_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/labels{/name}',
                     'releases_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/releases{/id}',
                     'deployments_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/deployments',
                     'created_at': '2020-02-07T21:02:05Z', 'updated_at': '2020-02-07T21:02:07Z',
                     'pushed_at': '2020-02-07T20:50:21Z', 'git_url': 'git://github.com/cdp2323/SSW555DSYZ.git',
                     'ssh_url': 'git@github.com:cdp2323/SSW555DSYZ.git',
                     'clone_url': 'https://github.com/cdp2323/SSW555DSYZ.git',
                     'svn_url': 'https://github.com/cdp2323/SSW555DSYZ', 'homepage': None, 'size': 0,
                     'stargazers_count': 0, 'watchers_count': 0, 'language': None, 'has_issues': False,
                     'has_projects': True, 'has_downloads': True, 'has_wiki': True, 'has_pages': False,
                     'forks_count': 0, 'mirror_url': None, 'archived': False, 'disabled': False, 'open_issues_count': 0,
                     'license': None, 'forks': 0, 'open_issues': 0, 'watchers': 0, 'default_branch': 'master'},
                    {'id': 237124126, 'node_id': 'MDEwOlJlcG9zaXRvcnkyMzcxMjQxMjY=', 'name': 'SSW567-HW01',
                     'full_name': 'cdp2323/SSW567-HW01', 'private': False,
                     'owner': {'login': 'cdp2323', 'id': 57602737, 'node_id': 'MDQ6VXNlcjU3NjAyNzM3',
                               'avatar_url': 'https://avatars1.githubusercontent.com/u/57602737?v=4', 'gravatar_id': '',
                               'url': 'https://api.github.com/users/cdp2323', 'html_url': 'https://github.com/cdp2323',
                               'followers_url': 'https://api.github.com/users/cdp2323/followers',
                               'following_url': 'https://api.github.com/users/cdp2323/following{/other_user}',
                               'gists_url': 'https://api.github.com/users/cdp2323/gists{/gist_id}',
                               'starred_url': 'https://api.github.com/users/cdp2323/starred{/owner}{/repo}',
                               'subscriptions_url': 'https://api.github.com/users/cdp2323/subscriptions',
                               'organizations_url': 'https://api.github.com/users/cdp2323/orgs',
                               'repos_url': 'https://api.github.com/users/cdp2323/repos',
                               'events_url': 'https://api.github.com/users/cdp2323/events{/privacy}',
                               'received_events_url': 'https://api.github.com/users/cdp2323/received_events',
                               'type': 'User', 'site_admin': False},
                     'html_url': 'https://github.com/cdp2323/SSW567-HW01', 'description': None, 'fork': False,
                     'url': 'https://api.github.com/repos/cdp2323/SSW567-HW01',
                     'forks_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/forks',
                     'keys_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/keys{/key_id}',
                     'collaborators_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/collaborators{/collaborator}',
                     'teams_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/teams',
                     'hooks_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/hooks',
                     'issue_events_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/issues/events{/number}',
                     'events_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/events',
                     'assignees_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/assignees{/user}',
                     'branches_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/branches{/branch}',
                     'tags_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/tags',
                     'blobs_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/git/blobs{/sha}',
                     'git_tags_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/git/tags{/sha}',
                     'git_refs_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/git/refs{/sha}',
                     'trees_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/git/trees{/sha}',
                     'statuses_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/statuses/{sha}',
                     'languages_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/languages',
                     'stargazers_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/stargazers',
                     'contributors_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/contributors',
                     'subscribers_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/subscribers',
                     'subscription_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/subscription',
                     'commits_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/commits{/sha}',
                     'git_commits_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/git/commits{/sha}',
                     'comments_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/comments{/number}',
                     'issue_comment_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/issues/comments{/number}',
                     'contents_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/contents/{+path}',
                     'compare_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/compare/{base}...{head}',
                     'merges_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/merges',
                     'archive_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/{archive_format}{/ref}',
                     'downloads_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/downloads',
                     'issues_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/issues{/number}',
                     'pulls_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/pulls{/number}',
                     'milestones_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/milestones{/number}',
                     'notifications_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/notifications{?since,all,participating}',
                     'labels_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/labels{/name}',
                     'releases_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/releases{/id}',
                     'deployments_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/deployments',
                     'created_at': '2020-01-30T02:25:08Z', 'updated_at': '2020-01-30T03:02:51Z',
                     'pushed_at': '2020-01-30T03:02:50Z', 'git_url': 'git://github.com/cdp2323/SSW567-HW01.git',
                     'ssh_url': 'git@github.com:cdp2323/SSW567-HW01.git',
                     'clone_url': 'https://github.com/cdp2323/SSW567-HW01.git',
                     'svn_url': 'https://github.com/cdp2323/SSW567-HW01', 'homepage': None, 'size': 255,
                     'stargazers_count': 0, 'watchers_count': 0, 'language': 'Python', 'has_issues': True,
                     'has_projects': True, 'has_downloads': True, 'has_wiki': True, 'has_pages': False,
                     'forks_count': 0, 'mirror_url': None, 'archived': False, 'disabled': False, 'open_issues_count': 0,
                     'license': None, 'forks': 0, 'open_issues': 0, 'watchers': 0, 'default_branch': 'master'},
                    {'id': 239214807, 'node_id': 'MDEwOlJlcG9zaXRvcnkyMzkyMTQ4MDc=', 'name': 'Triangle567',
                     'full_name': 'cdp2323/Triangle567', 'private': False,
                     'owner': {'login': 'cdp2323', 'id': 57602737, 'node_id': 'MDQ6VXNlcjU3NjAyNzM3',
                               'avatar_url': 'https://avatars1.githubusercontent.com/u/57602737?v=4', 'gravatar_id': '',
                               'url': 'https://api.github.com/users/cdp2323', 'html_url': 'https://github.com/cdp2323',
                               'followers_url': 'https://api.github.com/users/cdp2323/followers',
                               'following_url': 'https://api.github.com/users/cdp2323/following{/other_user}',
                               'gists_url': 'https://api.github.com/users/cdp2323/gists{/gist_id}',
                               'starred_url': 'https://api.github.com/users/cdp2323/starred{/owner}{/repo}',
                               'subscriptions_url': 'https://api.github.com/users/cdp2323/subscriptions',
                               'organizations_url': 'https://api.github.com/users/cdp2323/orgs',
                               'repos_url': 'https://api.github.com/users/cdp2323/repos',
                               'events_url': 'https://api.github.com/users/cdp2323/events{/privacy}',
                               'received_events_url': 'https://api.github.com/users/cdp2323/received_events',
                               'type': 'User', 'site_admin': False},
                     'html_url': 'https://github.com/cdp2323/Triangle567', 'description': None, 'fork': False,
                     'url': 'https://api.github.com/repos/cdp2323/Triangle567',
                     'forks_url': 'https://api.github.com/repos/cdp2323/Triangle567/forks',
                     'keys_url': 'https://api.github.com/repos/cdp2323/Triangle567/keys{/key_id}',
                     'collaborators_url': 'https://api.github.com/repos/cdp2323/Triangle567/collaborators{/collaborator}',
                     'teams_url': 'https://api.github.com/repos/cdp2323/Triangle567/teams',
                     'hooks_url': 'https://api.github.com/repos/cdp2323/Triangle567/hooks',
                     'issue_events_url': 'https://api.github.com/repos/cdp2323/Triangle567/issues/events{/number}',
                     'events_url': 'https://api.github.com/repos/cdp2323/Triangle567/events',
                     'assignees_url': 'https://api.github.com/repos/cdp2323/Triangle567/assignees{/user}',
                     'branches_url': 'https://api.github.com/repos/cdp2323/Triangle567/branches{/branch}',
                     'tags_url': 'https://api.github.com/repos/cdp2323/Triangle567/tags',
                     'blobs_url': 'https://api.github.com/repos/cdp2323/Triangle567/git/blobs{/sha}',
                     'git_tags_url': 'https://api.github.com/repos/cdp2323/Triangle567/git/tags{/sha}',
                     'git_refs_url': 'https://api.github.com/repos/cdp2323/Triangle567/git/refs{/sha}',
                     'trees_url': 'https://api.github.com/repos/cdp2323/Triangle567/git/trees{/sha}',
                     'statuses_url': 'https://api.github.com/repos/cdp2323/Triangle567/statuses/{sha}',
                     'languages_url': 'https://api.github.com/repos/cdp2323/Triangle567/languages',
                     'stargazers_url': 'https://api.github.com/repos/cdp2323/Triangle567/stargazers',
                     'contributors_url': 'https://api.github.com/repos/cdp2323/Triangle567/contributors',
                     'subscribers_url': 'https://api.github.com/repos/cdp2323/Triangle567/subscribers',
                     'subscription_url': 'https://api.github.com/repos/cdp2323/Triangle567/subscription',
                     'commits_url': 'https://api.github.com/repos/cdp2323/Triangle567/commits{/sha}',
                     'git_commits_url': 'https://api.github.com/repos/cdp2323/Triangle567/git/commits{/sha}',
                     'comments_url': 'https://api.github.com/repos/cdp2323/Triangle567/comments{/number}',
                     'issue_comment_url': 'https://api.github.com/repos/cdp2323/Triangle567/issues/comments{/number}',
                     'contents_url': 'https://api.github.com/repos/cdp2323/Triangle567/contents/{+path}',
                     'compare_url': 'https://api.github.com/repos/cdp2323/Triangle567/compare/{base}...{head}',
                     'merges_url': 'https://api.github.com/repos/cdp2323/Triangle567/merges',
                     'archive_url': 'https://api.github.com/repos/cdp2323/Triangle567/{archive_format}{/ref}',
                     'downloads_url': 'https://api.github.com/repos/cdp2323/Triangle567/downloads',
                     'issues_url': 'https://api.github.com/repos/cdp2323/Triangle567/issues{/number}',
                     'pulls_url': 'https://api.github.com/repos/cdp2323/Triangle567/pulls{/number}',
                     'milestones_url': 'https://api.github.com/repos/cdp2323/Triangle567/milestones{/number}',
                     'notifications_url': 'https://api.github.com/repos/cdp2323/Triangle567/notifications{?since,all,participating}',
                     'labels_url': 'https://api.github.com/repos/cdp2323/Triangle567/labels{/name}',
                     'releases_url': 'https://api.github.com/repos/cdp2323/Triangle567/releases{/id}',
                     'deployments_url': 'https://api.github.com/repos/cdp2323/Triangle567/deployments',
                     'created_at': '2020-02-08T22:41:42Z', 'updated_at': '2020-02-10T20:15:10Z',
                     'pushed_at': '2020-02-10T20:15:08Z', 'git_url': 'git://github.com/cdp2323/Triangle567.git',
                     'ssh_url': 'git@github.com:cdp2323/Triangle567.git',
                     'clone_url': 'https://github.com/cdp2323/Triangle567.git',
                     'svn_url': 'https://github.com/cdp2323/Triangle567', 'homepage': None, 'size': 505,
                     'stargazers_count': 0, 'watchers_count': 0, 'language': 'Python', 'has_issues': True,
                     'has_projects': True, 'has_downloads': True, 'has_wiki': True, 'has_pages': False,
                     'forks_count': 0, 'mirror_url': None, 'archived': False, 'disabled': False, 'open_issues_count': 0,
                     'license': None, 'forks': 0, 'open_issues': 0, 'watchers': 0, 'default_branch': 'master'}]
        mocked_req.return_value = MockedRes(response)
        self.assertEqual(get_api('cdp2323'), response)

    def test_get_repo(self):
        response = [{'id': 241715376, 'node_id': 'MDEwOlJlcG9zaXRvcnkyNDE3MTUzNzY=', 'name': 'GitHubApi567',
                     'full_name': 'cdp2323/GitHubApi567', 'private': False,
                     'owner': {'login': 'cdp2323', 'id': 57602737, 'node_id': 'MDQ6VXNlcjU3NjAyNzM3',
                               'avatar_url': 'https://avatars1.githubusercontent.com/u/57602737?v=4',
                               'gravatar_id': '', 'url': 'https://api.github.com/users/cdp2323',
                               'html_url': 'https://github.com/cdp2323',
                               'followers_url': 'https://api.github.com/users/cdp2323/followers',
                               'following_url': 'https://api.github.com/users/cdp2323/following{/other_user}',
                               'gists_url': 'https://api.github.com/users/cdp2323/gists{/gist_id}',
                               'starred_url': 'https://api.github.com/users/cdp2323/starred{/owner}{/repo}',
                               'subscriptions_url': 'https://api.github.com/users/cdp2323/subscriptions',
                               'organizations_url': 'https://api.github.com/users/cdp2323/orgs',
                               'repos_url': 'https://api.github.com/users/cdp2323/repos',
                               'events_url': 'https://api.github.com/users/cdp2323/events{/privacy}',
                               'received_events_url': 'https://api.github.com/users/cdp2323/received_events',
                               'type': 'User', 'site_admin': False},
                     'html_url': 'https://github.com/cdp2323/GitHubApi567', 'description': None, 'fork': False,
                     'url': 'https://api.github.com/repos/cdp2323/GitHubApi567',
                     'forks_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/forks',
                     'keys_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/keys{/key_id}',
                     'collaborators_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/collaborators{/collaborator}',
                     'teams_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/teams',
                     'hooks_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/hooks',
                     'issue_events_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/issues/events{/number}',
                     'events_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/events',
                     'assignees_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/assignees{/user}',
                     'branches_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/branches{/branch}',
                     'tags_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/tags',
                     'blobs_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/git/blobs{/sha}',
                     'git_tags_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/git/tags{/sha}',
                     'git_refs_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/git/refs{/sha}',
                     'trees_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/git/trees{/sha}',
                     'statuses_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/statuses/{sha}',
                     'languages_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/languages',
                     'stargazers_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/stargazers',
                     'contributors_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/contributors',
                     'subscribers_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/subscribers',
                     'subscription_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/subscription',
                     'commits_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/commits{/sha}',
                     'git_commits_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/git/commits{/sha}',
                     'comments_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/comments{/number}',
                     'issue_comment_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/issues/comments{/number}',
                     'contents_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/contents/{+path}',
                     'compare_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/compare/{base}...{head}',
                     'merges_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/merges',
                     'archive_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/{archive_format}{/ref}',
                     'downloads_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/downloads',
                     'issues_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/issues{/number}',
                     'pulls_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/pulls{/number}',
                     'milestones_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/milestones{/number}',
                     'notifications_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/notifications{?since,all,participating}',
                     'labels_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/labels{/name}',
                     'releases_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/releases{/id}',
                     'deployments_url': 'https://api.github.com/repos/cdp2323/GitHubApi567/deployments',
                     'created_at': '2020-02-19T20:11:27Z', 'updated_at': '2020-02-20T00:05:44Z',
                     'pushed_at': '2020-02-26T21:07:29Z', 'git_url': 'git://github.com/cdp2323/GitHubApi567.git',
                     'ssh_url': 'git@github.com:cdp2323/GitHubApi567.git',
                     'clone_url': 'https://github.com/cdp2323/GitHubApi567.git',
                     'svn_url': 'https://github.com/cdp2323/GitHubApi567', 'homepage': None, 'size': 30,
                     'stargazers_count': 0, 'watchers_count': 0, 'language': 'Python', 'has_issues': True,
                     'has_projects': True, 'has_downloads': True, 'has_wiki': True, 'has_pages': False,
                     'forks_count': 0, 'mirror_url': None, 'archived': False, 'disabled': False,
                     'open_issues_count': 0, 'license': None, 'forks': 0, 'open_issues': 0, 'watchers': 0,
                     'default_branch': 'master'},
                    {'id': 236403982, 'node_id': 'MDEwOlJlcG9zaXRvcnkyMzY0MDM5ODI=', 'name': 'hw567',
                     'full_name': 'cdp2323/hw567', 'private': False,
                     'owner': {'login': 'cdp2323', 'id': 57602737, 'node_id': 'MDQ6VXNlcjU3NjAyNzM3',
                               'avatar_url': 'https://avatars1.githubusercontent.com/u/57602737?v=4',
                               'gravatar_id': '', 'url': 'https://api.github.com/users/cdp2323',
                               'html_url': 'https://github.com/cdp2323',
                               'followers_url': 'https://api.github.com/users/cdp2323/followers',
                               'following_url': 'https://api.github.com/users/cdp2323/following{/other_user}',
                               'gists_url': 'https://api.github.com/users/cdp2323/gists{/gist_id}',
                               'starred_url': 'https://api.github.com/users/cdp2323/starred{/owner}{/repo}',
                               'subscriptions_url': 'https://api.github.com/users/cdp2323/subscriptions',
                               'organizations_url': 'https://api.github.com/users/cdp2323/orgs',
                               'repos_url': 'https://api.github.com/users/cdp2323/repos',
                               'events_url': 'https://api.github.com/users/cdp2323/events{/privacy}',
                               'received_events_url': 'https://api.github.com/users/cdp2323/received_events',
                               'type': 'User', 'site_admin': False}, 'html_url': 'https://github.com/cdp2323/hw567',
                     'description': None, 'fork': False, 'url': 'https://api.github.com/repos/cdp2323/hw567',
                     'forks_url': 'https://api.github.com/repos/cdp2323/hw567/forks',
                     'keys_url': 'https://api.github.com/repos/cdp2323/hw567/keys{/key_id}',
                     'collaborators_url': 'https://api.github.com/repos/cdp2323/hw567/collaborators{/collaborator}',
                     'teams_url': 'https://api.github.com/repos/cdp2323/hw567/teams',
                     'hooks_url': 'https://api.github.com/repos/cdp2323/hw567/hooks',
                     'issue_events_url': 'https://api.github.com/repos/cdp2323/hw567/issues/events{/number}',
                     'events_url': 'https://api.github.com/repos/cdp2323/hw567/events',
                     'assignees_url': 'https://api.github.com/repos/cdp2323/hw567/assignees{/user}',
                     'branches_url': 'https://api.github.com/repos/cdp2323/hw567/branches{/branch}',
                     'tags_url': 'https://api.github.com/repos/cdp2323/hw567/tags',
                     'blobs_url': 'https://api.github.com/repos/cdp2323/hw567/git/blobs{/sha}',
                     'git_tags_url': 'https://api.github.com/repos/cdp2323/hw567/git/tags{/sha}',
                     'git_refs_url': 'https://api.github.com/repos/cdp2323/hw567/git/refs{/sha}',
                     'trees_url': 'https://api.github.com/repos/cdp2323/hw567/git/trees{/sha}',
                     'statuses_url': 'https://api.github.com/repos/cdp2323/hw567/statuses/{sha}',
                     'languages_url': 'https://api.github.com/repos/cdp2323/hw567/languages',
                     'stargazers_url': 'https://api.github.com/repos/cdp2323/hw567/stargazers',
                     'contributors_url': 'https://api.github.com/repos/cdp2323/hw567/contributors',
                     'subscribers_url': 'https://api.github.com/repos/cdp2323/hw567/subscribers',
                     'subscription_url': 'https://api.github.com/repos/cdp2323/hw567/subscription',
                     'commits_url': 'https://api.github.com/repos/cdp2323/hw567/commits{/sha}',
                     'git_commits_url': 'https://api.github.com/repos/cdp2323/hw567/git/commits{/sha}',
                     'comments_url': 'https://api.github.com/repos/cdp2323/hw567/comments{/number}',
                     'issue_comment_url': 'https://api.github.com/repos/cdp2323/hw567/issues/comments{/number}',
                     'contents_url': 'https://api.github.com/repos/cdp2323/hw567/contents/{+path}',
                     'compare_url': 'https://api.github.com/repos/cdp2323/hw567/compare/{base}...{head}',
                     'merges_url': 'https://api.github.com/repos/cdp2323/hw567/merges',
                     'archive_url': 'https://api.github.com/repos/cdp2323/hw567/{archive_format}{/ref}',
                     'downloads_url': 'https://api.github.com/repos/cdp2323/hw567/downloads',
                     'issues_url': 'https://api.github.com/repos/cdp2323/hw567/issues{/number}',
                     'pulls_url': 'https://api.github.com/repos/cdp2323/hw567/pulls{/number}',
                     'milestones_url': 'https://api.github.com/repos/cdp2323/hw567/milestones{/number}',
                     'notifications_url': 'https://api.github.com/repos/cdp2323/hw567/notifications{?since,all,participating}',
                     'labels_url': 'https://api.github.com/repos/cdp2323/hw567/labels{/name}',
                     'releases_url': 'https://api.github.com/repos/cdp2323/hw567/releases{/id}',
                     'deployments_url': 'https://api.github.com/repos/cdp2323/hw567/deployments',
                     'created_at': '2020-01-27T01:52:58Z', 'updated_at': '2020-01-30T02:28:22Z',
                     'pushed_at': '2020-01-27T01:53:02Z', 'git_url': 'git://github.com/cdp2323/hw567.git',
                     'ssh_url': 'git@github.com:cdp2323/hw567.git',
                     'clone_url': 'https://github.com/cdp2323/hw567.git',
                     'svn_url': 'https://github.com/cdp2323/hw567', 'homepage': None, 'size': 0,
                     'stargazers_count': 0, 'watchers_count': 0, 'language': 'Python', 'has_issues': True,
                     'has_projects': True, 'has_downloads': True, 'has_wiki': True, 'has_pages': False,
                     'forks_count': 0, 'mirror_url': None, 'archived': False, 'disabled': False,
                     'open_issues_count': 0, 'license': None, 'forks': 0, 'open_issues': 0, 'watchers': 0,
                     'default_branch': 'master'},
                    {'id': 220853365, 'node_id': 'MDEwOlJlcG9zaXRvcnkyMjA4NTMzNjU=', 'name': 'hw810',
                     'full_name': 'cdp2323/hw810', 'private': False,
                     'owner': {'login': 'cdp2323', 'id': 57602737, 'node_id': 'MDQ6VXNlcjU3NjAyNzM3',
                               'avatar_url': 'https://avatars1.githubusercontent.com/u/57602737?v=4',
                               'gravatar_id': '', 'url': 'https://api.github.com/users/cdp2323',
                               'html_url': 'https://github.com/cdp2323',
                               'followers_url': 'https://api.github.com/users/cdp2323/followers',
                               'following_url': 'https://api.github.com/users/cdp2323/following{/other_user}',
                               'gists_url': 'https://api.github.com/users/cdp2323/gists{/gist_id}',
                               'starred_url': 'https://api.github.com/users/cdp2323/starred{/owner}{/repo}',
                               'subscriptions_url': 'https://api.github.com/users/cdp2323/subscriptions',
                               'organizations_url': 'https://api.github.com/users/cdp2323/orgs',
                               'repos_url': 'https://api.github.com/users/cdp2323/repos',
                               'events_url': 'https://api.github.com/users/cdp2323/events{/privacy}',
                               'received_events_url': 'https://api.github.com/users/cdp2323/received_events',
                               'type': 'User', 'site_admin': False}, 'html_url': 'https://github.com/cdp2323/hw810',
                     'description': None, 'fork': False, 'url': 'https://api.github.com/repos/cdp2323/hw810',
                     'forks_url': 'https://api.github.com/repos/cdp2323/hw810/forks',
                     'keys_url': 'https://api.github.com/repos/cdp2323/hw810/keys{/key_id}',
                     'collaborators_url': 'https://api.github.com/repos/cdp2323/hw810/collaborators{/collaborator}',
                     'teams_url': 'https://api.github.com/repos/cdp2323/hw810/teams',
                     'hooks_url': 'https://api.github.com/repos/cdp2323/hw810/hooks',
                     'issue_events_url': 'https://api.github.com/repos/cdp2323/hw810/issues/events{/number}',
                     'events_url': 'https://api.github.com/repos/cdp2323/hw810/events',
                     'assignees_url': 'https://api.github.com/repos/cdp2323/hw810/assignees{/user}',
                     'branches_url': 'https://api.github.com/repos/cdp2323/hw810/branches{/branch}',
                     'tags_url': 'https://api.github.com/repos/cdp2323/hw810/tags',
                     'blobs_url': 'https://api.github.com/repos/cdp2323/hw810/git/blobs{/sha}',
                     'git_tags_url': 'https://api.github.com/repos/cdp2323/hw810/git/tags{/sha}',
                     'git_refs_url': 'https://api.github.com/repos/cdp2323/hw810/git/refs{/sha}',
                     'trees_url': 'https://api.github.com/repos/cdp2323/hw810/git/trees{/sha}',
                     'statuses_url': 'https://api.github.com/repos/cdp2323/hw810/statuses/{sha}',
                     'languages_url': 'https://api.github.com/repos/cdp2323/hw810/languages',
                     'stargazers_url': 'https://api.github.com/repos/cdp2323/hw810/stargazers',
                     'contributors_url': 'https://api.github.com/repos/cdp2323/hw810/contributors',
                     'subscribers_url': 'https://api.github.com/repos/cdp2323/hw810/subscribers',
                     'subscription_url': 'https://api.github.com/repos/cdp2323/hw810/subscription',
                     'commits_url': 'https://api.github.com/repos/cdp2323/hw810/commits{/sha}',
                     'git_commits_url': 'https://api.github.com/repos/cdp2323/hw810/git/commits{/sha}',
                     'comments_url': 'https://api.github.com/repos/cdp2323/hw810/comments{/number}',
                     'issue_comment_url': 'https://api.github.com/repos/cdp2323/hw810/issues/comments{/number}',
                     'contents_url': 'https://api.github.com/repos/cdp2323/hw810/contents/{+path}',
                     'compare_url': 'https://api.github.com/repos/cdp2323/hw810/compare/{base}...{head}',
                     'merges_url': 'https://api.github.com/repos/cdp2323/hw810/merges',
                     'archive_url': 'https://api.github.com/repos/cdp2323/hw810/{archive_format}{/ref}',
                     'downloads_url': 'https://api.github.com/repos/cdp2323/hw810/downloads',
                     'issues_url': 'https://api.github.com/repos/cdp2323/hw810/issues{/number}',
                     'pulls_url': 'https://api.github.com/repos/cdp2323/hw810/pulls{/number}',
                     'milestones_url': 'https://api.github.com/repos/cdp2323/hw810/milestones{/number}',
                     'notifications_url': 'https://api.github.com/repos/cdp2323/hw810/notifications{?since,all,participating}',
                     'labels_url': 'https://api.github.com/repos/cdp2323/hw810/labels{/name}',
                     'releases_url': 'https://api.github.com/repos/cdp2323/hw810/releases{/id}',
                     'deployments_url': 'https://api.github.com/repos/cdp2323/hw810/deployments',
                     'created_at': '2019-11-10T21:24:54Z', 'updated_at': '2019-11-10T23:26:00Z',
                     'pushed_at': '2019-11-16T23:16:47Z', 'git_url': 'git://github.com/cdp2323/hw810.git',
                     'ssh_url': 'git@github.com:cdp2323/hw810.git',
                     'clone_url': 'https://github.com/cdp2323/hw810.git',
                     'svn_url': 'https://github.com/cdp2323/hw810', 'homepage': None, 'size': 1190,
                     'stargazers_count': 0, 'watchers_count': 0, 'language': 'Python', 'has_issues': True,
                     'has_projects': True, 'has_downloads': True, 'has_wiki': True, 'has_pages': False,
                     'forks_count': 0, 'mirror_url': None, 'archived': False, 'disabled': False,
                     'open_issues_count': 0, 'license': None, 'forks': 0, 'open_issues': 0, 'watchers': 0,
                     'default_branch': 'master'},
                    {'id': 239021902, 'node_id': 'MDEwOlJlcG9zaXRvcnkyMzkwMjE5MDI=', 'name': 'SSW555DSYZ',
                     'full_name': 'cdp2323/SSW555DSYZ', 'private': False,
                     'owner': {'login': 'cdp2323', 'id': 57602737, 'node_id': 'MDQ6VXNlcjU3NjAyNzM3',
                               'avatar_url': 'https://avatars1.githubusercontent.com/u/57602737?v=4',
                               'gravatar_id': '', 'url': 'https://api.github.com/users/cdp2323',
                               'html_url': 'https://github.com/cdp2323',
                               'followers_url': 'https://api.github.com/users/cdp2323/followers',
                               'following_url': 'https://api.github.com/users/cdp2323/following{/other_user}',
                               'gists_url': 'https://api.github.com/users/cdp2323/gists{/gist_id}',
                               'starred_url': 'https://api.github.com/users/cdp2323/starred{/owner}{/repo}',
                               'subscriptions_url': 'https://api.github.com/users/cdp2323/subscriptions',
                               'organizations_url': 'https://api.github.com/users/cdp2323/orgs',
                               'repos_url': 'https://api.github.com/users/cdp2323/repos',
                               'events_url': 'https://api.github.com/users/cdp2323/events{/privacy}',
                               'received_events_url': 'https://api.github.com/users/cdp2323/received_events',
                               'type': 'User', 'site_admin': False},
                     'html_url': 'https://github.com/cdp2323/SSW555DSYZ', 'description': 'SSW555 Group Project',
                     'fork': True, 'url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ',
                     'forks_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/forks',
                     'keys_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/keys{/key_id}',
                     'collaborators_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/collaborators{/collaborator}',
                     'teams_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/teams',
                     'hooks_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/hooks',
                     'issue_events_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/issues/events{/number}',
                     'events_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/events',
                     'assignees_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/assignees{/user}',
                     'branches_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/branches{/branch}',
                     'tags_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/tags',
                     'blobs_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/git/blobs{/sha}',
                     'git_tags_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/git/tags{/sha}',
                     'git_refs_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/git/refs{/sha}',
                     'trees_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/git/trees{/sha}',
                     'statuses_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/statuses/{sha}',
                     'languages_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/languages',
                     'stargazers_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/stargazers',
                     'contributors_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/contributors',
                     'subscribers_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/subscribers',
                     'subscription_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/subscription',
                     'commits_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/commits{/sha}',
                     'git_commits_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/git/commits{/sha}',
                     'comments_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/comments{/number}',
                     'issue_comment_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/issues/comments{/number}',
                     'contents_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/contents/{+path}',
                     'compare_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/compare/{base}...{head}',
                     'merges_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/merges',
                     'archive_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/{archive_format}{/ref}',
                     'downloads_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/downloads',
                     'issues_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/issues{/number}',
                     'pulls_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/pulls{/number}',
                     'milestones_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/milestones{/number}',
                     'notifications_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/notifications{?since,all,participating}',
                     'labels_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/labels{/name}',
                     'releases_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/releases{/id}',
                     'deployments_url': 'https://api.github.com/repos/cdp2323/SSW555DSYZ/deployments',
                     'created_at': '2020-02-07T21:02:05Z', 'updated_at': '2020-02-07T21:02:07Z',
                     'pushed_at': '2020-02-07T20:50:21Z', 'git_url': 'git://github.com/cdp2323/SSW555DSYZ.git',
                     'ssh_url': 'git@github.com:cdp2323/SSW555DSYZ.git',
                     'clone_url': 'https://github.com/cdp2323/SSW555DSYZ.git',
                     'svn_url': 'https://github.com/cdp2323/SSW555DSYZ', 'homepage': None, 'size': 0,
                     'stargazers_count': 0, 'watchers_count': 0, 'language': None, 'has_issues': False,
                     'has_projects': True, 'has_downloads': True, 'has_wiki': True, 'has_pages': False,
                     'forks_count': 0, 'mirror_url': None, 'archived': False, 'disabled': False,
                     'open_issues_count': 0, 'license': None, 'forks': 0, 'open_issues': 0, 'watchers': 0,
                     'default_branch': 'master'},
                    {'id': 237124126, 'node_id': 'MDEwOlJlcG9zaXRvcnkyMzcxMjQxMjY=', 'name': 'SSW567-HW01',
                     'full_name': 'cdp2323/SSW567-HW01', 'private': False,
                     'owner': {'login': 'cdp2323', 'id': 57602737, 'node_id': 'MDQ6VXNlcjU3NjAyNzM3',
                               'avatar_url': 'https://avatars1.githubusercontent.com/u/57602737?v=4',
                               'gravatar_id': '', 'url': 'https://api.github.com/users/cdp2323',
                               'html_url': 'https://github.com/cdp2323',
                               'followers_url': 'https://api.github.com/users/cdp2323/followers',
                               'following_url': 'https://api.github.com/users/cdp2323/following{/other_user}',
                               'gists_url': 'https://api.github.com/users/cdp2323/gists{/gist_id}',
                               'starred_url': 'https://api.github.com/users/cdp2323/starred{/owner}{/repo}',
                               'subscriptions_url': 'https://api.github.com/users/cdp2323/subscriptions',
                               'organizations_url': 'https://api.github.com/users/cdp2323/orgs',
                               'repos_url': 'https://api.github.com/users/cdp2323/repos',
                               'events_url': 'https://api.github.com/users/cdp2323/events{/privacy}',
                               'received_events_url': 'https://api.github.com/users/cdp2323/received_events',
                               'type': 'User', 'site_admin': False},
                     'html_url': 'https://github.com/cdp2323/SSW567-HW01', 'description': None, 'fork': False,
                     'url': 'https://api.github.com/repos/cdp2323/SSW567-HW01',
                     'forks_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/forks',
                     'keys_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/keys{/key_id}',
                     'collaborators_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/collaborators{/collaborator}',
                     'teams_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/teams',
                     'hooks_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/hooks',
                     'issue_events_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/issues/events{/number}',
                     'events_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/events',
                     'assignees_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/assignees{/user}',
                     'branches_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/branches{/branch}',
                     'tags_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/tags',
                     'blobs_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/git/blobs{/sha}',
                     'git_tags_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/git/tags{/sha}',
                     'git_refs_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/git/refs{/sha}',
                     'trees_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/git/trees{/sha}',
                     'statuses_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/statuses/{sha}',
                     'languages_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/languages',
                     'stargazers_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/stargazers',
                     'contributors_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/contributors',
                     'subscribers_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/subscribers',
                     'subscription_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/subscription',
                     'commits_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/commits{/sha}',
                     'git_commits_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/git/commits{/sha}',
                     'comments_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/comments{/number}',
                     'issue_comment_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/issues/comments{/number}',
                     'contents_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/contents/{+path}',
                     'compare_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/compare/{base}...{head}',
                     'merges_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/merges',
                     'archive_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/{archive_format}{/ref}',
                     'downloads_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/downloads',
                     'issues_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/issues{/number}',
                     'pulls_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/pulls{/number}',
                     'milestones_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/milestones{/number}',
                     'notifications_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/notifications{?since,all,participating}',
                     'labels_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/labels{/name}',
                     'releases_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/releases{/id}',
                     'deployments_url': 'https://api.github.com/repos/cdp2323/SSW567-HW01/deployments',
                     'created_at': '2020-01-30T02:25:08Z', 'updated_at': '2020-01-30T03:02:51Z',
                     'pushed_at': '2020-01-30T03:02:50Z', 'git_url': 'git://github.com/cdp2323/SSW567-HW01.git',
                     'ssh_url': 'git@github.com:cdp2323/SSW567-HW01.git',
                     'clone_url': 'https://github.com/cdp2323/SSW567-HW01.git',
                     'svn_url': 'https://github.com/cdp2323/SSW567-HW01', 'homepage': None, 'size': 255,
                     'stargazers_count': 0, 'watchers_count': 0, 'language': 'Python', 'has_issues': True,
                     'has_projects': True, 'has_downloads': True, 'has_wiki': True, 'has_pages': False,
                     'forks_count': 0, 'mirror_url': None, 'archived': False, 'disabled': False,
                     'open_issues_count': 0, 'license': None, 'forks': 0, 'open_issues': 0, 'watchers': 0,
                     'default_branch': 'master'},
                    {'id': 239214807, 'node_id': 'MDEwOlJlcG9zaXRvcnkyMzkyMTQ4MDc=', 'name': 'Triangle567',
                     'full_name': 'cdp2323/Triangle567', 'private': False,
                     'owner': {'login': 'cdp2323', 'id': 57602737, 'node_id': 'MDQ6VXNlcjU3NjAyNzM3',
                               'avatar_url': 'https://avatars1.githubusercontent.com/u/57602737?v=4',
                               'gravatar_id': '', 'url': 'https://api.github.com/users/cdp2323',
                               'html_url': 'https://github.com/cdp2323',
                               'followers_url': 'https://api.github.com/users/cdp2323/followers',
                               'following_url': 'https://api.github.com/users/cdp2323/following{/other_user}',
                               'gists_url': 'https://api.github.com/users/cdp2323/gists{/gist_id}',
                               'starred_url': 'https://api.github.com/users/cdp2323/starred{/owner}{/repo}',
                               'subscriptions_url': 'https://api.github.com/users/cdp2323/subscriptions',
                               'organizations_url': 'https://api.github.com/users/cdp2323/orgs',
                               'repos_url': 'https://api.github.com/users/cdp2323/repos',
                               'events_url': 'https://api.github.com/users/cdp2323/events{/privacy}',
                               'received_events_url': 'https://api.github.com/users/cdp2323/received_events',
                               'type': 'User', 'site_admin': False},
                     'html_url': 'https://github.com/cdp2323/Triangle567', 'description': None, 'fork': False,
                     'url': 'https://api.github.com/repos/cdp2323/Triangle567',
                     'forks_url': 'https://api.github.com/repos/cdp2323/Triangle567/forks',
                     'keys_url': 'https://api.github.com/repos/cdp2323/Triangle567/keys{/key_id}',
                     'collaborators_url': 'https://api.github.com/repos/cdp2323/Triangle567/collaborators{/collaborator}',
                     'teams_url': 'https://api.github.com/repos/cdp2323/Triangle567/teams',
                     'hooks_url': 'https://api.github.com/repos/cdp2323/Triangle567/hooks',
                     'issue_events_url': 'https://api.github.com/repos/cdp2323/Triangle567/issues/events{/number}',
                     'events_url': 'https://api.github.com/repos/cdp2323/Triangle567/events',
                     'assignees_url': 'https://api.github.com/repos/cdp2323/Triangle567/assignees{/user}',
                     'branches_url': 'https://api.github.com/repos/cdp2323/Triangle567/branches{/branch}',
                     'tags_url': 'https://api.github.com/repos/cdp2323/Triangle567/tags',
                     'blobs_url': 'https://api.github.com/repos/cdp2323/Triangle567/git/blobs{/sha}',
                     'git_tags_url': 'https://api.github.com/repos/cdp2323/Triangle567/git/tags{/sha}',
                     'git_refs_url': 'https://api.github.com/repos/cdp2323/Triangle567/git/refs{/sha}',
                     'trees_url': 'https://api.github.com/repos/cdp2323/Triangle567/git/trees{/sha}',
                     'statuses_url': 'https://api.github.com/repos/cdp2323/Triangle567/statuses/{sha}',
                     'languages_url': 'https://api.github.com/repos/cdp2323/Triangle567/languages',
                     'stargazers_url': 'https://api.github.com/repos/cdp2323/Triangle567/stargazers',
                     'contributors_url': 'https://api.github.com/repos/cdp2323/Triangle567/contributors',
                     'subscribers_url': 'https://api.github.com/repos/cdp2323/Triangle567/subscribers',
                     'subscription_url': 'https://api.github.com/repos/cdp2323/Triangle567/subscription',
                     'commits_url': 'https://api.github.com/repos/cdp2323/Triangle567/commits{/sha}',
                     'git_commits_url': 'https://api.github.com/repos/cdp2323/Triangle567/git/commits{/sha}',
                     'comments_url': 'https://api.github.com/repos/cdp2323/Triangle567/comments{/number}',
                     'issue_comment_url': 'https://api.github.com/repos/cdp2323/Triangle567/issues/comments{/number}',
                     'contents_url': 'https://api.github.com/repos/cdp2323/Triangle567/contents/{+path}',
                     'compare_url': 'https://api.github.com/repos/cdp2323/Triangle567/compare/{base}...{head}',
                     'merges_url': 'https://api.github.com/repos/cdp2323/Triangle567/merges',
                     'archive_url': 'https://api.github.com/repos/cdp2323/Triangle567/{archive_format}{/ref}',
                     'downloads_url': 'https://api.github.com/repos/cdp2323/Triangle567/downloads',
                     'issues_url': 'https://api.github.com/repos/cdp2323/Triangle567/issues{/number}',
                     'pulls_url': 'https://api.github.com/repos/cdp2323/Triangle567/pulls{/number}',
                     'milestones_url': 'https://api.github.com/repos/cdp2323/Triangle567/milestones{/number}',
                     'notifications_url': 'https://api.github.com/repos/cdp2323/Triangle567/notifications{?since,all,participating}',
                     'labels_url': 'https://api.github.com/repos/cdp2323/Triangle567/labels{/name}',
                     'releases_url': 'https://api.github.com/repos/cdp2323/Triangle567/releases{/id}',
                     'deployments_url': 'https://api.github.com/repos/cdp2323/Triangle567/deployments',
                     'created_at': '2020-02-08T22:41:42Z', 'updated_at': '2020-02-10T20:15:10Z',
                     'pushed_at': '2020-02-10T20:15:08Z', 'git_url': 'git://github.com/cdp2323/Triangle567.git',
                     'ssh_url': 'git@github.com:cdp2323/Triangle567.git',
                     'clone_url': 'https://github.com/cdp2323/Triangle567.git',
                     'svn_url': 'https://github.com/cdp2323/Triangle567', 'homepage': None, 'size': 505,
                     'stargazers_count': 0, 'watchers_count': 0, 'language': 'Python', 'has_issues': True,
                     'has_projects': True, 'has_downloads': True, 'has_wiki': True, 'has_pages': False,
                     'forks_count': 0, 'mirror_url': None, 'archived': False, 'disabled': False,
                     'open_issues_count': 0, 'license': None, 'forks': 0, 'open_issues': 0, 'watchers': 0,
                     'default_branch': 'master'}]

        self.assertEqual(get_repo(response),
                         ['GitHubApi567', 'hw567', 'hw810', 'SSW555DSYZ', 'SSW567-HW01', 'Triangle567'])

    @mock.patch('retrieve_repo.get_commits')
    def test_get_commits(self, mocked_req):
        commits_list = [16, 2, 1, 1, 2, 7]
        mocked_req.return_value = commits_list
        userID = 'cdp2323'
        repo_list = ['GitHubApi567', 'hw567', 'hw810', 'SSW555DSYZ', 'SSW567-HW01', 'Triangle567']
        commits = get_commits(userID, repo_list)
        self.assertEqual(commits, commits_list)

    @mock.patch('retrieve_repo.get_output')
    def test_get_output(self, mocked_req):
        repo_list = ['GitHubApi567', 'hw567', 'hw810', 'SSW555DSYZ', 'SSW567-HW01', 'Triangle567']
        commits_list = [16, 2, 1, 1, 2, 7]
        output = ['Repo: GitHubApi567 Number of commits: 16', 'Repo: hw567 Number of commits: 2',
                  'Repo: hw810 Number of commits: 1', 'Repo: SSW555DSYZ Number of commits: 1',
                  'Repo: SSW567-HW01 Number of commits: 2', 'Repo: Triangle567 Number of commits: 7']
        mocked_req.return_value = output
        self.assertAlmostEqual(get_output(repo_list, commits_list), output)


if __name__ == "__main__":
    unittest.main()
